### ISSUE TITLE
using SaramaCluster to handle rebalance

### ISSUE THREAD

**Issue by prune998** [echojc/kafka-offset-exporter#4]
Do you have any Plan to use Sarama Cluster (https://github.com/bsm/sarama-cluster) instead of plain Sarama to handle the case of a Kafka broker going down ?

**Comment by echojc** [comment]
Sorry, no. Feel free to submit a PR, but I'm not sure that sarama-cluster would work with the current architecture, in which case it might be easier to write a new exporter.
